import type { GameSummary, GameDetail, GameEvent } from "./game";

export const mockEvents: GameEvent[] = [
  {
    event_id: "evt_001",
    game_id: "20260318_OB_LT",
    sequence: 1,
    timestamp: "2026-03-18T20:10:00+09:00",
    event_type: "single",
    result_label: "좌전 안타",
    zone_label: "좌익수 앞",
    rbi: 0,
    score_after: { away: 3, home: 2 },
    count_after: { balls: 0, strikes: 0, outs: 1 },
    bases_after: { first: true, second: true, third: false },
    importance: "medium",
  },
  {
    event_id: "evt_002",
    game_id: "20260318_OB_LT",
    sequence: 2,
    timestamp: "2026-03-18T20:12:00+09:00",
    event_type: "strikeout",
    result_label: "삼진",
    zone_label: "",
    rbi: 0,
    score_after: { away: 3, home: 2 },
    count_after: { balls: 0, strikes: 0, outs: 2 },
    bases_after: { first: true, second: true, third: false },
    importance: "low",
  },
  {
    event_id: "evt_003",
    game_id: "20260318_OB_LT",
    sequence: 3,
    timestamp: "2026-03-18T20:14:00+09:00",
    event_type: "double",
    result_label: "좌중간 2루타",
    zone_label: "좌중간",
    rbi: 2,
    score_after: { away: 3, home: 4 },
    count_after: { balls: 0, strikes: 0, outs: 2 },
    bases_after: { first: false, second: true, third: false },
    importance: "critical",
  },
  {
    event_id: "evt_004",
    game_id: "20260318_SS_HH",
    sequence: 1,
    timestamp: "2026-03-18T19:45:00+09:00",
    event_type: "homerun",
    result_label: "솔로 홈런",
    zone_label: "좌측 담장",
    rbi: 1,
    score_after: { away: 5, home: 1 },
    count_after: { balls: 0, strikes: 0, outs: 1 },
    bases_after: { first: false, second: false, third: false },
    importance: "high",
  },
  {
    event_id: "evt_005",
    game_id: "20260318_KT_NC",
    sequence: 1,
    timestamp: "2026-03-18T20:00:00+09:00",
    event_type: "walk",
    result_label: "볼넷",
    zone_label: "",
    rbi: 0,
    score_after: { away: 2, home: 2 },
    count_after: { balls: 0, strikes: 0, outs: 0 },
    bases_after: { first: true, second: false, third: false },
    importance: "medium",
  },
];

export const mockGames: GameSummary[] = [
  {
    game_id: "20260318_OB_LT",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "OB", name: "두산" },
    home_team: { code: "LT", name: "롯데" },
    score: { away: 3, home: 4 },
    inning: { number: 7, half: "bottom" },
    count: { balls: 1, strikes: 2, outs: 2 },
    bases: { first: false, second: true, third: false },
    situation_tags: ["close", "late", "chance"],
  },
  {
    game_id: "20260318_SS_HH",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "SS", name: "삼성" },
    home_team: { code: "HH", name: "한화" },
    score: { away: 5, home: 1 },
    inning: { number: 5, half: "top" },
    count: { balls: 0, strikes: 0, outs: 0 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
  },
  {
    game_id: "20260318_KT_NC",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "KT", name: "KT" },
    home_team: { code: "NC", name: "NC" },
    score: { away: 2, home: 2 },
    inning: { number: 8, half: "top" },
    count: { balls: 3, strikes: 1, outs: 1 },
    bases: { first: true, second: false, third: false },
    situation_tags: ["close", "late"],
  },
  {
    game_id: "20260318_LG_KW",
    status: "final",
    start_time: "2026-03-18T14:00:00+09:00",
    away_team: { code: "LG", name: "LG" },
    home_team: { code: "KW", name: "키움" },
    score: { away: 7, home: 3 },
    inning: { number: 9, half: "bottom" },
    count: { balls: 0, strikes: 0, outs: 3 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
  },
  {
    game_id: "20260318_SK_HT",
    status: "scheduled",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "SK", name: "SSG" },
    home_team: { code: "HT", name: "KIA" },
    score: { away: 0, home: 0 },
    inning: { number: 1, half: "top" },
    count: { balls: 0, strikes: 0, outs: 0 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
  },
];

export const mockGameDetails: Record<string, GameDetail> = {
  "20260318_OB_LT": {
    game_id: "20260318_OB_LT",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "OB", name: "두산" },
    home_team: { code: "LT", name: "롯데" },
    score: { away: 3, home: 4 },
    inning: { number: 7, half: "bottom" },
    count: { balls: 1, strikes: 2, outs: 2 },
    bases: { first: false, second: true, third: false },
    situation_tags: ["close", "late", "chance"],
    current_batter: { name: "전준우", team_code: "LT", order: 4, position: "RF" },
    current_pitcher: { name: "곽빈", team_code: "OB", throws: "R" },
    recent_events: mockEvents.filter((e) => e.game_id === "20260318_OB_LT"),
  },
  "20260318_SS_HH": {
    game_id: "20260318_SS_HH",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "SS", name: "삼성" },
    home_team: { code: "HH", name: "한화" },
    score: { away: 5, home: 1 },
    inning: { number: 5, half: "top" },
    count: { balls: 0, strikes: 0, outs: 0 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
    current_batter: { name: "구자욱", team_code: "SS", order: 3, position: "LF" },
    current_pitcher: { name: "문동주", team_code: "HH", throws: "R" },
    recent_events: mockEvents.filter((e) => e.game_id === "20260318_SS_HH"),
  },
  "20260318_KT_NC": {
    game_id: "20260318_KT_NC",
    status: "live",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "KT", name: "KT" },
    home_team: { code: "NC", name: "NC" },
    score: { away: 2, home: 2 },
    inning: { number: 8, half: "top" },
    count: { balls: 3, strikes: 1, outs: 1 },
    bases: { first: true, second: false, third: false },
    situation_tags: ["close", "late"],
    current_batter: { name: "강백호", team_code: "KT", order: 4, position: "1B" },
    current_pitcher: { name: "구창모", team_code: "NC", throws: "L" },
    recent_events: mockEvents.filter((e) => e.game_id === "20260318_KT_NC"),
  },
  "20260318_LG_KW": {
    game_id: "20260318_LG_KW",
    status: "final",
    start_time: "2026-03-18T14:00:00+09:00",
    away_team: { code: "LG", name: "LG" },
    home_team: { code: "KW", name: "키움" },
    score: { away: 7, home: 3 },
    inning: { number: 9, half: "bottom" },
    count: { balls: 0, strikes: 0, outs: 3 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
    current_batter: null,
    current_pitcher: null,
    recent_events: [],
  },
  "20260318_SK_HT": {
    game_id: "20260318_SK_HT",
    status: "scheduled",
    start_time: "2026-03-18T18:30:00+09:00",
    away_team: { code: "SK", name: "SSG" },
    home_team: { code: "HT", name: "KIA" },
    score: { away: 0, home: 0 },
    inning: { number: 1, half: "top" },
    count: { balls: 0, strikes: 0, outs: 0 },
    bases: { first: false, second: false, third: false },
    situation_tags: [],
    current_batter: null,
    current_pitcher: null,
    recent_events: [],
  },
};
