"""Mock fixture data for development."""

from .models import (
    Bases,
    BatterInfo,
    Count,
    EventType,
    GameDetail,
    GameEvent,
    GameStatus,
    GameSummary,
    Importance,
    Inning,
    InningHalf,
    PitcherInfo,
    Score,
    SituationTag,
    TeamInfo,
)

MOCK_EVENTS: list[GameEvent] = [
    GameEvent(
        event_id="evt_001",
        game_id="20260318_OB_LT",
        sequence=1,
        timestamp="2026-03-18T20:10:00+09:00",
        event_type=EventType.single,
        result_label="좌전 안타",
        zone_label="좌익수 앞",
        rbi=0,
        score_after=Score(away=3, home=2),
        count_after=Count(balls=0, strikes=0, outs=1),
        bases_after=Bases(first=True, second=True, third=False),
        importance=Importance.medium,
    ),
    GameEvent(
        event_id="evt_002",
        game_id="20260318_OB_LT",
        sequence=2,
        timestamp="2026-03-18T20:12:00+09:00",
        event_type=EventType.strikeout,
        result_label="삼진",
        zone_label="",
        rbi=0,
        score_after=Score(away=3, home=2),
        count_after=Count(balls=0, strikes=0, outs=2),
        bases_after=Bases(first=True, second=True, third=False),
        importance=Importance.low,
    ),
    GameEvent(
        event_id="evt_003",
        game_id="20260318_OB_LT",
        sequence=3,
        timestamp="2026-03-18T20:14:00+09:00",
        event_type=EventType.double,
        result_label="좌중간 2루타",
        zone_label="좌중간",
        rbi=2,
        score_after=Score(away=3, home=4),
        count_after=Count(balls=0, strikes=0, outs=2),
        bases_after=Bases(first=False, second=True, third=False),
        importance=Importance.critical,
    ),
    GameEvent(
        event_id="evt_004",
        game_id="20260318_SS_HH",
        sequence=1,
        timestamp="2026-03-18T19:45:00+09:00",
        event_type=EventType.homerun,
        result_label="솔로 홈런",
        zone_label="좌측 담장",
        rbi=1,
        score_after=Score(away=5, home=1),
        count_after=Count(balls=0, strikes=0, outs=1),
        bases_after=Bases(first=False, second=False, third=False),
        importance=Importance.high,
    ),
    GameEvent(
        event_id="evt_005",
        game_id="20260318_KT_NC",
        sequence=1,
        timestamp="2026-03-18T20:00:00+09:00",
        event_type=EventType.walk,
        result_label="볼넷",
        zone_label="",
        rbi=0,
        score_after=Score(away=2, home=2),
        count_after=Count(balls=0, strikes=0, outs=0),
        bases_after=Bases(first=True, second=False, third=False),
        importance=Importance.medium,
    ),
]

MOCK_GAMES: list[GameSummary] = [
    GameSummary(
        game_id="20260318_OB_LT",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="OB", name="두산"),
        home_team=TeamInfo(code="LT", name="롯데"),
        score=Score(away=3, home=4),
        inning=Inning(number=7, half=InningHalf.bottom),
        count=Count(balls=1, strikes=2, outs=2),
        bases=Bases(first=False, second=True, third=False),
        situation_tags=[SituationTag.close, SituationTag.late, SituationTag.chance],
    ),
    GameSummary(
        game_id="20260318_SS_HH",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="SS", name="삼성"),
        home_team=TeamInfo(code="HH", name="한화"),
        score=Score(away=5, home=1),
        inning=Inning(number=5, half=InningHalf.top),
        count=Count(balls=0, strikes=0, outs=0),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
    ),
    GameSummary(
        game_id="20260318_KT_NC",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="KT", name="KT"),
        home_team=TeamInfo(code="NC", name="NC"),
        score=Score(away=2, home=2),
        inning=Inning(number=8, half=InningHalf.top),
        count=Count(balls=3, strikes=1, outs=1),
        bases=Bases(first=True, second=False, third=False),
        situation_tags=[SituationTag.close, SituationTag.late],
    ),
    GameSummary(
        game_id="20260318_LG_KW",
        status=GameStatus.final,
        start_time="2026-03-18T14:00:00+09:00",
        away_team=TeamInfo(code="LG", name="LG"),
        home_team=TeamInfo(code="KW", name="키움"),
        score=Score(away=7, home=3),
        inning=Inning(number=9, half=InningHalf.bottom),
        count=Count(balls=0, strikes=0, outs=3),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
    ),
    GameSummary(
        game_id="20260318_SK_HT",
        status=GameStatus.scheduled,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="SK", name="SSG"),
        home_team=TeamInfo(code="HT", name="KIA"),
        score=Score(away=0, home=0),
        inning=Inning(number=1, half=InningHalf.top),
        count=Count(balls=0, strikes=0, outs=0),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
    ),
]

MOCK_GAME_DETAILS: dict[str, GameDetail] = {
    "20260318_OB_LT": GameDetail(
        game_id="20260318_OB_LT",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="OB", name="두산"),
        home_team=TeamInfo(code="LT", name="롯데"),
        score=Score(away=3, home=4),
        inning=Inning(number=7, half=InningHalf.bottom),
        count=Count(balls=1, strikes=2, outs=2),
        bases=Bases(first=False, second=True, third=False),
        situation_tags=[SituationTag.close, SituationTag.late, SituationTag.chance],
        current_batter=BatterInfo(name="전준우", team_code="LT", order=4, position="RF"),
        current_pitcher=PitcherInfo(name="곽빈", team_code="OB", throws="R"),
        recent_events=[e for e in MOCK_EVENTS if e.game_id == "20260318_OB_LT"],
    ),
    "20260318_SS_HH": GameDetail(
        game_id="20260318_SS_HH",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="SS", name="삼성"),
        home_team=TeamInfo(code="HH", name="한화"),
        score=Score(away=5, home=1),
        inning=Inning(number=5, half=InningHalf.top),
        count=Count(balls=0, strikes=0, outs=0),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
        current_batter=BatterInfo(name="구자욱", team_code="SS", order=3, position="LF"),
        current_pitcher=PitcherInfo(name="문동주", team_code="HH", throws="R"),
        recent_events=[e for e in MOCK_EVENTS if e.game_id == "20260318_SS_HH"],
    ),
    "20260318_KT_NC": GameDetail(
        game_id="20260318_KT_NC",
        status=GameStatus.live,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="KT", name="KT"),
        home_team=TeamInfo(code="NC", name="NC"),
        score=Score(away=2, home=2),
        inning=Inning(number=8, half=InningHalf.top),
        count=Count(balls=3, strikes=1, outs=1),
        bases=Bases(first=True, second=False, third=False),
        situation_tags=[SituationTag.close, SituationTag.late],
        current_batter=BatterInfo(name="강백호", team_code="KT", order=4, position="1B"),
        current_pitcher=PitcherInfo(name="구창모", team_code="NC", throws="L"),
        recent_events=[e for e in MOCK_EVENTS if e.game_id == "20260318_KT_NC"],
    ),
    "20260318_LG_KW": GameDetail(
        game_id="20260318_LG_KW",
        status=GameStatus.final,
        start_time="2026-03-18T14:00:00+09:00",
        away_team=TeamInfo(code="LG", name="LG"),
        home_team=TeamInfo(code="KW", name="키움"),
        score=Score(away=7, home=3),
        inning=Inning(number=9, half=InningHalf.bottom),
        count=Count(balls=0, strikes=0, outs=3),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
        current_batter=None,
        current_pitcher=None,
        recent_events=[],
    ),
    "20260318_SK_HT": GameDetail(
        game_id="20260318_SK_HT",
        status=GameStatus.scheduled,
        start_time="2026-03-18T18:30:00+09:00",
        away_team=TeamInfo(code="SK", name="SSG"),
        home_team=TeamInfo(code="HT", name="KIA"),
        score=Score(away=0, home=0),
        inning=Inning(number=1, half=InningHalf.top),
        count=Count(balls=0, strikes=0, outs=0),
        bases=Bases(first=False, second=False, third=False),
        situation_tags=[],
        current_batter=None,
        current_pitcher=None,
        recent_events=[],
    ),
}
